# Generated by Django 4.0.2 on 2022-02-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rating',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
