# Generated by Django 4.0.2 on 2022-02-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_remove_userprofile_rating_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='static/chess/profile.default.jpg', null=True, upload_to=''),
        ),
    ]
