# Generated by Django 4.0.2 on 2022-02-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_memepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemePost',
            new_name='Post',
        ),
    ]
