# Generated by Django 4.0.2 on 2022-02-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0006_userprofile_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='No Bio...', null=True),
        ),
    ]
