# Generated by Django 4.0.2 on 2022-02-17 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0007_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='points',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
