# Generated by Django 4.0.2 on 2022-02-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0007_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourites',
            field=models.ManyToManyField(related_name='favourite', to='chess.UserProfile'),
        ),
    ]
