# Generated by Django 4.0.2 on 2022-02-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0008_rename_points_userprofile_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='chess.UserProfile'),
        ),
    ]
