# Generated by Django 4.0.2 on 2022-02-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0009_alter_post_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
