# Generated by Django 4.0.2 on 2022-02-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0011_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to='chess.UserProfile'),
        ),
    ]
