# Generated by Django 4.0.2 on 2022-02-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0012_remove_post_video_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
